/**
 * SEO asset generator for S&S Associates.
 * Writes mirror copies under seo-static/ (NOT public/) — Next.js 16 forbids
 * public/robots.txt or public/sitemap.xml when app/robots.js and app/sitemap.js exist.
 * Live site uses /robots.txt and /sitemap.xml from the App Router only.
 *
 * Usage: NEXT_PUBLIC_SITE_URL=... MONGODB_URI=... node scripts/generate-seo.js
 * Or:    npm run seo
 */

/* eslint-disable no-console */
const fs = require("fs");
const path = require("path");
const mongoose = require("mongoose");

const ROOT = path.join(__dirname, "..");
/** Static copies for FTP / nginx mirrors only — do not place in public/ */
const SEO_STATIC = path.join(ROOT, "seo-static");

function getBaseUrl() {
  const raw = process.env.NEXT_PUBLIC_SITE_URL || "https://www.ss-associates.pk";
  return String(raw).replace(/\/+$/, "");
}

function escapeXml(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function writeRobots(base) {
  const body = [
    "# Generated by scripts/generate-seo.js — align with src/app/robots.js",
    "User-agent: *",
    "Allow: /",
    "Disallow: /user/",
    "Disallow: /api/",
    "Disallow: /login",
    "Disallow: /setup",
    "",
    `Sitemap: ${base}/sitemap.xml`,
    "",
  ].join("\n");
  fs.mkdirSync(SEO_STATIC, { recursive: true });
  fs.writeFileSync(path.join(SEO_STATIC, "robots.txt"), body, "utf8");
  console.log("[generate-seo] Wrote seo-static/robots.txt");
}

function buildStaticUrlEntries(base) {
  const now = new Date().toISOString();
  return [
    { loc: base, lastmod: now, changefreq: "daily", priority: "1.0" },
    { loc: `${base}/about`, lastmod: now, changefreq: "weekly", priority: "0.8" },
    { loc: `${base}/services`, lastmod: now, changefreq: "weekly", priority: "0.8" },
    { loc: `${base}/projects`, lastmod: now, changefreq: "weekly", priority: "0.8" },
    { loc: `${base}/contact`, lastmod: now, changefreq: "weekly", priority: "0.8" },
    { loc: `${base}/privacy-policy`, lastmod: now, changefreq: "monthly", priority: "0.5" },
    { loc: `${base}/terms-%26-conditions`, lastmod: now, changefreq: "monthly", priority: "0.5" },
  ];
}

function writeSitemapXml(entries) {
  const urls = entries
    .map(
      (e) => `  <url>
    <loc>${escapeXml(e.loc)}</loc>
    <lastmod>${escapeXml(e.lastmod)}</lastmod>
    <changefreq>${escapeXml(e.changefreq)}</changefreq>
    <priority>${escapeXml(e.priority)}</priority>
  </url>`
    )
    .join("\n");
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
  fs.writeFileSync(path.join(SEO_STATIC, "sitemap.xml"), xml, "utf8");
  console.log("[generate-seo] Wrote seo-static/sitemap.xml with", entries.length, "URLs");
}

function sampleOrganizationJsonLd(base) {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "S&S Associates",
    url: base,
  };
}

function sampleBreadcrumbJsonLd(base) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: `${base}/` },
      { "@type": "ListItem", position: 2, name: "Projects", item: `${base}/projects` },
    ],
  };
}

function logSchemaSamples(base) {
  const org = sampleOrganizationJsonLd(base);
  const crumbs = sampleBreadcrumbJsonLd(base);
  console.log("[generate-seo] Sample JSON-LD (Organization):");
  console.log(JSON.stringify(org, null, 2));
  console.log("[generate-seo] Sample JSON-LD (BreadcrumbList):");
  console.log(JSON.stringify(crumbs, null, 2));
}

function logUrls(entries) {
  console.log("[generate-seo] URL list:");
  entries.forEach((e) => console.log("  -", e.loc));
}

async function main() {
  const base = getBaseUrl();
  console.log("[generate-seo] NEXT_PUBLIC_SITE_URL →", base);

  writeRobots(base);

  let entries = buildStaticUrlEntries(base);
  const uri = process.env.MONGODB_URI;

  if (!uri) {
    console.warn("[generate-seo] MONGODB_URI not set — dynamic service/project URLs omitted");
    writeSitemapXml(entries);
    logUrls(entries);
    logSchemaSamples(base);
    process.exit(0);
    return;
  }

  try {
    await mongoose.connect(uri);
    const db = mongoose.connection.db;
    const services = await db.collection("services").find({}).project({ updatedAt: 1, createdAt: 1 }).toArray();
    const projects = await db.collection("projects").find({}).project({ updatedAt: 1, createdAt: 1 }).toArray();

    const nowIso = new Date().toISOString();
    function toIso(d) {
      if (!d) return nowIso;
      const dt = d instanceof Date ? d : new Date(d);
      return Number.isNaN(dt.getTime()) ? nowIso : dt.toISOString();
    }
    for (const s of services) {
      const id = s._id.toString();
      entries.push({
        loc: `${base}/services/${id}`,
        lastmod: toIso(s.updatedAt || s.createdAt),
        changefreq: "monthly",
        priority: "0.7",
      });
    }
    for (const p of projects) {
      const id = p._id.toString();
      entries.push({
        loc: `${base}/projects/${id}`,
        lastmod: toIso(p.updatedAt || p.createdAt),
        changefreq: "monthly",
        priority: "0.7",
      });
    }
    console.log("[generate-seo] Added", services.length, "service URLs,", projects.length, "project URLs");
    await mongoose.disconnect();
  } catch (err) {
    console.warn("[generate-seo] MongoDB skipped:", err.message || err);
  }

  writeSitemapXml(entries);
  logUrls(entries);
  logSchemaSamples(base);
  console.log("[generate-seo] Done.");
}

main().catch((e) => {
  console.error("[generate-seo] Fatal:", e);
  process.exit(1);
});
